/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminSidebar: typeof import('./src/components/AdminSidebar.vue')['default']
    AuditLogDetailDialog: typeof import('./src/components/audit/AuditLogDetailDialog.vue')['default']
    BatchReviewDialog: typeof import('./src/components/ai-content/BatchReviewDialog.vue')['default']
    ContentReviewDialog: typeof import('./src/components/ai-content/ContentReviewDialog.vue')['default']
    CourseFormDialog: typeof import('./src/components/course/CourseFormDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    EnhancedAuthLayout: typeof import('./src/components/auth/EnhancedAuthLayout.vue')['default']
    EnhancedLoginForm: typeof import('./src/components/auth/EnhancedLoginForm.vue')['default']
    ErrorBoundary: typeof import('./src/components/ErrorBoundary.vue')['default']
    ImportUsersDialog: typeof import('./src/components/user/ImportUsersDialog.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    PolicyFormDialog: typeof import('./src/components/policy/PolicyFormDialog.vue')['default']
    QuotaFormDialog: typeof import('./src/components/quota/QuotaFormDialog.vue')['default']
    ResourceUploadDialog: typeof import('./src/components/resource/ResourceUploadDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TenantActivityLogs: typeof import('./src/components/tenant/TenantActivityLogs.vue')['default']
    TenantConfiguration: typeof import('./src/components/tenant/TenantConfiguration.vue')['default']
    TenantDetailDialog: typeof import('./src/components/tenant/TenantDetailDialog.vue')['default']
    TenantFormDialog: typeof import('./src/components/tenant/TenantFormDialog.vue')['default']
    TenantQuotaManagement: typeof import('./src/components/tenant/TenantQuotaManagement.vue')['default']
    TenantUserManagement: typeof import('./src/components/tenant/TenantUserManagement.vue')['default']
    UserDetailDialog: typeof import('./src/components/user/UserDetailDialog.vue')['default']
    UserFormDialog: typeof import('./src/components/user/UserFormDialog.vue')['default']
  }
}
